### ISSUE TITLE
Shortcut customization 

### ISSUE THREAD

**Issue by LukasDrsman** [dylanaraps/sowm#10]
Is there a way to use single-key shortcuts? How does the the customization of shortcuts work?

**Comment by tjtf2** [comment]
You can specify the mod as 0 in order to use just the key:

{0,  XK_Print, run, {.com=scrot}} will run the scrot command whenever you press just the printscreen key

**Comment by LukyIsHere** [comment]
what if I want to run commands with parameters?

**Comment by tjtf2** [comment]
Well the commands are actually not defined at the same time as the keys.

You specify commands and their parameters before you map them to something, for example:

```
...
const char *ff[] = {"st", "-e", "fff", NULL};
... /* Here are the key mappings */
```

The above command is a array of strings, it will run the program `fff` inside of `st` when you pressed the corect keybinding(which you have to specify yourself).

It gets "translated" to the following shell command
```
$ st -e fff
```

Is this what you meant by parameters?

**Comment by LukyIsHere** [comment]
yes

**Comment by LukyIsHere** [comment]
How do I use spacebar? I didn't find it in Keyboard.h. Is there a way to use it?

**Comment by tjtf2** [comment]
I think `XK_space` should work

Example:
`{Mod, XK_space, run, { .com=somecommand}}`

I think/hope it works(can't test it right now, i'm on mobile)
