### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Magnus-101** [dylanaraps/sowm#108]
Hello, do you have plans to update sowm? I have several problems when using it, the command to make focus cycle works at times, after a few hours I have to press the combination of keys several times to make it work or reboot the machine, also when opening the browser and for example opening another instance (incognito etc) if I close a browser window the browser closes completely, ranger and fff do not work for me to see image previews (w3m, ueberzug), in dwm which is my other WM I don't have those problems, I love the sowm project but I think it has bugs. Greetings

**Comment by ghost** [comment]
yes and also when i cycle through one window and kill it it will either crach sowm or freezes sowm

**Comment by Magnus-101** [comment]
Yeah  ;)

**Comment by mitko17** [comment]
I'm not sure if it works but... I think the browser "bug" can be fixed by using this patch:
https://github.com/dylanaraps/sowm-patches/blob/master/patches/sowm-normal-kill.patch

Found it here: https://github.com/dylanaraps/sowm/issues/54

**Comment by dylanaraps** [comment]
I no longer have time to dedicate to this project (nor do I use Xorg anyhow). Am happy to accept
patches to fix bugs (if any bugs exist). The only bug possibly valid is the focus cycle one (though
it has never happened to me). Kill behavior is intentional and w3m-img/ueberzug are hacks..
