### ISSUE TITLE
Recommended quit command.

### ISSUE THREAD

**Issue by mrneilypops** [dylanaraps/sowm#13]
Hi,
I would like to setup a key combo to quit sowm eg like dwm Alt+Shift+q
Would killall sowm be OK?
Can you recommend a command?

**Comment by dylanaraps** [comment]
I personally use `pkill x` (*`pkill sowm` works too*). `killall sowm` should work too (*though I haven't personally tested it*). :+1:

**Comment by mrneilypops** [comment]
Should this work? Not working for me...
`const char* quit[]    = {"pkill x",    0};`
`{MOD|ShiftMask, XK_q, run, {.com = quit}},`

**Comment by tjtf2** [comment]
Use `const char *quit[] = {"pkill", "x", 0}`

**Comment by mrneilypops** [comment]
Working! Thanks!
I am enjoying sowm on Void linux (+pfetch)
![2019-10-19-165659_1920x1080_scrot](https://user-images.githubusercontent.com/1450448/67147100-008e8d00-f292-11e9-909f-87407013fb89.png)

**Comment by mrneilypops** [comment]
One final question. I am unable to find the scrot app 'scr'
I am using scrot at the moment.
Can you advise where I might find the 'scr' app?

**Comment by dylanaraps** [comment]
`scr` is just a script I wrote to take a screenshot and store it by date.

```sh
#!/usr/bin/env bash
#
# Take a screenshot.

scr_dir=~/Pictures/Screenshots

printf -v date '%(%F)T' -1
printf -v time '%(%I-%M-%S)T' -1

mkdir -p "$scr_dir/$date"
scr=$scr_dir/$date/$date-$time

import -window root "$scr".jpg
cp -f "$scr".jpg "$scr_dir/current.jpg"
```

You can set the key to `scrot`, `import`, your own script or anything you like really.

**Comment by mrneilypops** [comment]
Thanks.

**Comment by medgar123** [comment]
You can bind a key to this matricidal script to quit sowm:

    {MOD|ShiftMask, XK_q, run, {.com = (const char *[]){"/bin/sh", "-c", "kill -HUP $PPID", 0}}},
