### ISSUE TITLE
Multihead support

### ISSUE THREAD

**Issue by dab** [dylanaraps/sowm#19]
Hi there, testing `sowm` on my working laptop and it's not working well with multihead setup. For example, if i dragged window to secondary display and press `MOD+F` to go fullscreen - it moves the window back to primary display and making it fullscreen there. I suppose it is not expected behavior. Would be nice to have a separate desktops on different screens. A-la `dwm`. And keybindings to move windows from one screen to another.
Thanks for your time.

**Comment by astier** [comment]
Support for a second monitor would be nice. Not built-in but as a patch. The problem for me is that although I also don't use a second monitor sometimes I need to use a projector for presentations. And it kind of sucks to install a second wm/de just for this purpose. Other than that its a very good project. Clean code. Thx.

**Comment by koutsie** [comment]
this would be extremely cool

**Comment by koutsie** [comment]
https://github.com/Leon-Plickat created an primitive patch for this and it seems to work awesomely, maybe https://github.com/dylanaraps/sowm/pull/28 is the start of something awesome?

**Comment by dylanaraps** [comment]
The primitive multi monitor patch has been pushed to master, please try it out.

**Comment by dab** [comment]
Thanks, window positioning working  properly. 
The main issue with current approach - the way how it control desktops. It force you to use both multihead screens at the same time. When you press `super+2` it switches all the screens together. The same way `Openbox` working.
And i prefer `dwm` way of handling this - you can have separate desktops on different screens. When you pressing `super+2` on first screen - it will change desktop only there.
Hope to see it here sometime soonish.
With optimism!

**Comment by dylanaraps** [comment]
Closing this as we have a patch now (minus workspaces). Please open another issue here: https://github.com/dylanaraps/sowm-patches
