### ISSUE TITLE
New rect-to-move patch function?

### ISSUE THREAD

**Issue by vaskark** [dylanaraps/sowm#33]
Dumb question. I've just applied this patch but am not sure what it does. Can someone help?

Edit: Ok. It allows resizing the window without having to grab the edges, which was awkward just using a trackpad. Thank God! Closing ...

**Comment by SeungheonOh** [comment]
[Here](https://www.reddit.com/r/unixporn/comments/eah3ak/oc_ive_wrote_sowm_patch_for_rectangle_style/) is a video demonstration.

**Comment by vaskark** [comment]
@SeungheonOh  Wow. That is different than what I assumed :)

I’ve applied the patch but it isn’t working for me atm. I imagine it’s a left-click & drag gesture with a mouse. My trackpad ain’t working with it. I’ll have to try my mouse when I get a chance.

**Comment by SeungheonOh** [comment]
Thanks!
