### ISSUE TITLE
fix coding style in sowm.c

### ISSUE THREAD

**Issue by kiedtl** [dylanaraps/sowm#37]
I think it would be a good idea to fix code style in `sowm.c` to conform to usual style.

- move function prototypes to `sowm.h` (also global variables, data structures, basically anything that's not a function.)
- add prototypes for function that don't have them
- add some formatting to the `Makefile`, for heaven's sake

- OPTIONALLY compile with `-Wold-style-declaration -Wmissing-prototype -Werror` for stricter code style

If you think this a good idea I can submit a PR for this

Thanks, kiedtl

**Comment by dylanaraps** [comment]
> move function prototypes to sowm.h (also global variables, data structures, basically anything that's not a function.)

I don't see this as necessary given the size of `sowm`.

 > change function declarations from

This was cut off?

> add prototypes for function that don't have them

Will fix this one.

> add some formatting to the Makefile, for heaven's sake

Care to elaborate?

> OPTIONALLY compile with -Wold-style-declaration -Wmissing-prototype -Werror for stricter code style

I agree to `-Wmissing-prototype`. :+1:

**Comment by kiedtl** [comment]
> This was cut off?

yeah, I wasn't sure whether it was a good idea.

> Care to elaborate?

Well, the variables at the top don't have any spacing in them, which made them a pain to read (well, at least for me anyway):
```
CFLAGS+= -blah --blah=blah
```
if spaces were added:
```
CLFLAGS    += -blah --blah=blah
```
I guess it really doesn't matter though, it's not like the average user is going to fuss about a Makefile's formatting.
