### ISSUE TITLE
Windows-to-workspaces stopped working

### ISSUE THREAD

**Issue by vaskark** [dylanaraps/sowm#42]
I've noticed recently that the window-to-workspace function has stopped working for me. MOD+Shift+ws just opens the workspace without moving the window there. Has anyone else noticed this? I've applied the normal-kill, almost-tags-1.0, wheelresize, and 2bswm patches (although it still didn't work with a fresh sowm install, patch free).

Here is the output to [make](https://pastebin.com/bHsjfRu2). Lots of warnings :)

Thanks! Let me know if more info is needed.

**Comment by SeungheonOh** [comment]
The warnings are about some simple type cast, and prototype; they are not critical

**Comment by vaskark** [comment]
@SeungheonOh Thanks for responding. I assumed the errors were benign but I thought it best to include anyway.
Is window-to-workspace working okay for you?

**Comment by SeungheonOh** [comment]
@vaskark I'll let you know as soon as I test it; I assume it might be this afternoon. Since, I normally don't use multiple work spaces often, I don't really know. 
One possibility is that, multiple patches can crush original functionality.

**Comment by ncmprhnsbl** [comment]
i noticed this too... pretty sure my tests included patch free(some weeks ago)

**Comment by SeungheonOh** [comment]
@ncmprhnsbl Thanks for letting us know! I’ll take a deeper look!

**Comment by SeungheonOh** [comment]
@dylanaraps Hey, I found that the win_to_ws() and ws_go() is okay, but the problem is that sowm cannot properly differentiate the mod mask key code and the mod+shiftmask key code. For example, pressing Mod+Shift+1 not only runs win_to_ws but also ws_go, when I put win_to_ws on another key without Shift mask, it worked as intended.

**Comment by SeungheonOh** [comment]
Looks like it's fixed

**Comment by vaskark** [comment]
Awesome! Thx guys.
