### ISSUE TITLE
Window initializing process

### ISSUE THREAD

**Issue by SeungheonOh** [dylanaraps/sowm#45]
The windows that had been opened before sowm is not recognized properly and sowm does not have control on those windows. 

For example, if I run st before sowm, and try to move or control the pre-opened st, sowm fails(sometimes with Segfault)

**Comment by dylanaraps** [comment]
This is known and not something I particularly care about.

Patches welcome.

**Comment by SeungheonOh** [comment]
Oh gotcha 👍
