### ISSUE TITLE
Strange 2bswm-patch resize behaviour

### ISSUE THREAD

**Issue by vaskark** [dylanaraps/sowm#47]
I applied the 2bswm patch and it was working, with move and resize behaving as expected. However, something changed recently. The resize effect seems to be applying to the left and top of the window, as opposed to the right and bottom (as usual).

Example: MOD+Shift+j should be resizing the window DOWN, making it larger vertically. Instead, it's resizing UP (at the top of the window instead of the bottom).

Hopefully I've explained this usefully.

Also, most patches are being applied to sown.c. But when I do a `git pull` it keeps getting overwritten and I have to apply my patches all over again. Is there a better method for doing this?

Thanks.

Also: what does the sowm-init patch do? It was be nice if patch functionality was stated (when it isn't obvious :)

**Comment by SeungheonOh** [comment]
Check, working on it! Thanks for letting me know. Patch is broken anyways after the update; I'm in process of making new one

**Comment by SeungheonOh** [comment]
fixed, enjoy!

**Comment by SeungheonOh** [comment]
sowm-init adds ability for sowm to start at middle of the session when there's pre-opend clients. When you try to interact with pre-opend client without sowm-init patch, segfault is going to occur. Even though it is not a huge deal for normal user, who starts sowm at the x-startup, it is quite annoying for me since I start x only with sxhkd and lunch wm of my choice afterwards. 

check here for more information: #45

**Comment by vaskark** [comment]
@SeungheonOh Thanks so much!

Also, I just noticed in sowm-wheelresize.patch that:

```
-    for (int i=1; i<4; i+=2)
+    for (int i=1; i<6; i++)
```

But sowm.c has:

`for (i = 1; i < 4; i += 2)`

Doing the usual replacement produced errors (obviously).

**Comment by SeungheonOh** [comment]
That is required since it sets wheel buttons to be captured.

**Comment by vaskark** [comment]
So the new line is:

`for (i = 1; 1 < 6, i ++)` 

without the `int`

**Comment by SeungheonOh** [comment]
I assume, I'll make new patch is afternoon!

**Comment by vaskark** [comment]
Awesome. Thanks so much for all your hard work. And to all the other devs.
