### ISSUE TITLE
Multiple monitor support?

### ISSUE THREAD

**Issue by lonkaars** [dylanaraps/sowm#52]
I'm doing my first Arch Linux install with sowm, but when I maximize a window, it stretches over both my displays. I don't know if this is an issue with sowm or if it's my display settings, but I have tried seperating X screens and setting up Xinerama, but that didn't work.

**Comment by koutsie** [comment]
*hey, here: https://github.com/dylanaraps/sowm-patches/blob/master/patches/sowm-primitive-multimonitor.patch*

**Comment by lonkaars** [comment]
```
$ git apply ~/sowm-patches/patches/sowm-primitive-multimonitor.patch
error: patch failed: Makefile:1
error: Makefile: patch does not apply
error: patch failed: sowm.c:48
error: sowm.c: patch does not apply
```

Doesn't work

**Comment by dylanaraps** [comment]
The patch needs rebasing to work on the latest release. The original author has not yet done this. See https://github.com/dylanaraps/sowm/pull/28
