### ISSUE TITLE
sowm not launching?

### ISSUE THREAD

**Issue by IbrahimFadel** [dylanaraps/sowm#53]
Hi, this is sort of a stupid question, but i can't get sowm to launch properly.

I cloned the repo, copied the config, ran ```make``` then ```sudo make install```

Finally, i added ```exec sowm``` to the end of my .xinitrc

When i reboot, i have a black screen, and nothing launches. Anything i may have missed?
Here's my full .xinitrc:

```if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[ -f ~/.Xresources ] && xrdb ~/.Xresources

exec sowm
```

Any idea where i've gone wrong? Thanks

**Comment by dylanaraps** [comment]
Sounds like it's working to me. `sowm` does nothing at startup.

**Comment by IbrahimFadel** [comment]
Yeah, maybe it's because i'm using lightdm? Does xinitrc not matter to lightdm?

**Comment by dylanaraps** [comment]
I don't think it does. NOTE: sowm doesn't track windows launched before it has opened.

**Comment by IbrahimFadel** [comment]
Sorry, i think i misunderstood your first comment. I don't think my x server is actually launching with``` sowm```. I can press ```alt+f2``` and login through command line

**Comment by dylanaraps** [comment]
Try launching it through `startx`.

**Comment by IbrahimFadel** [comment]
I'm away from my computer right now, but i'll try when i'm home

**Comment by SeungheonOh** [comment]
Any updates?

**Comment by IbrahimFadel** [comment]
```startx``` launches sowm properly (i have a black screen with a cursor). However, i have to first press ```alt+f2``` then sign in through command line then run ```startx```. Is there a reason it's not working properly?

**Comment by SeungheonOh** [comment]
I assume you use DE. Not sure since I have not used any DE before, but most of DE lunches some default WM in boot so it is expected for you to start X from other session. Here's my suggestion, try to boot from runlevel 3(booting without Gui at bootup) and start X session from there. ( This is the cleanest and safe way )
Options 2 is you could try to configure DE setting to start sowm with DE.

**Comment by IbrahimFadel** [comment]
Alright, i've temporarily disabled my DE, and i can just run ```startx``` after login. But one tiny quick question. What is the default Mod key? I can't bring up a terminal/dmenu or anything

**Comment by SeungheonOh** [comment]
Mod4mask is Super key( or windows key)

**Comment by IbrahimFadel** [comment]
Ok thanks so much

**Comment by SeungheonOh** [comment]
@IbrahimFadel My pleasure!
In my opinion, DE is often heavy and goes against the principle of sowm: having simple, clean, and light workspace. Many people who follows the minimalistic principles, including me, only use WM.

**Comment by IbrahimFadel** [comment]
That makes sense. I'm currently just trying a bunch of different setups, trying to find what's right for me.
