### ISSUE TITLE
[Question] Close child windows?

### ISSUE THREAD

**Issue by lonkaars** [dylanaraps/sowm#54]
Is there a way to close child windows, without killing the entire process? I use ripcord, and you have to close the call window in order to leave the call, but currently I can only do this using mod4+q and restarting ripcord.

**Comment by dylanaraps** [comment]
See: https://github.com/dylanaraps/sowm-patches/blob/master/patches/sowm-normal-kill.patch

**Comment by 808-cowbell** [comment]
I may be doing this wrong, but I don't think this patch successfully applies on 1.6.
Here is the command I am using, and the output I get:
`curl https://raw.githubusercontent.com/dylanaraps/sowm-patches/master/patches/sowm-normal-kill.patch | git apply`
`error: patch failed: sowm.c:165
error: sowm.c: patch does not apply`
I've also tested this from master and it didn't seem to work, either. Help would be appreciated, thank you in advance.
