### ISSUE TITLE
Recent build error on Ubuntu 19.10

### ISSUE THREAD

**Issue by vaskark** [dylanaraps/sowm#61]
I've encountered this error with the latest git:

[pastebin](https://pastebin.com/hzwvQ7w2)

Hope this helps.

**Comment by SeungheonOh** [comment]
Your xlib does seem to be properly installed

**Comment by vaskark** [comment]
Does not? Ok. I tried reinstalling libx11-dev. Same error.

**Comment by SeungheonOh** [comment]
Or hmm, then it has to be improperly linked

**Comment by vaskark** [comment]
Hmm. I ran `sudo ldconfig` before my last reply. Still nope.

**Comment by SeungheonOh** [comment]
Try to build with pkg-config

**Comment by dylanaraps** [comment]
https://github.com/dylanaraps/sowm/releases/tag/1.6

**Comment by vaskark** [comment]
Dang. That was fast. Thanks so much. This wm is great to use.

**Comment by SeungheonOh** [comment]
Wow didnt know that
