### ISSUE TITLE
Compiling after new changes

### ISSUE THREAD

**Issue by remembertoremind** [dylanaraps/sowm#63]
After I've cloned the repo, I make my changes to `config.h` and run `make` and `make install`. Thereafter, I can start `sowm` as intended. However, if I make new changes to `config.h` and run `make` again I get the message

    make: Nothing to be done for 'all'.

Afterwards I tried to run `make install` which works as intended but the newer changes are not applied. Am I missing some flags?

Great wm btw! :)

**Comment by dylanaraps** [comment]
Run `make clean` first.
