### ISSUE TITLE
Window outline/border

### ISSUE THREAD

**Issue by EnricoMonese** [dylanaraps/sowm#72]
Would it be possible to add coloured borders around the windows? 
I could possibly do a patch myself but have to clue where to start or if it would be possible. Any pointers?

**Comment by SeungheonOh** [comment]
Check out rounded window patch, it works in a same way, but the difference is the color and shape.
Good luck

**Comment by EnricoMonese** [comment]
> I can write a patch if you want, just let me know.

If you don't mind doing it sure! Thank you!

Gave a look at the rounded corners patch,  doesn't seem too complex but I'm not familiar with X apis

**Comment by SeungheonOh** [comment]
Checkout #74
