### ISSUE TITLE
Tiling mode

### ISSUE THREAD

**Issue by plasmoduck** [dylanaraps/sowm#75]
Can you make a patch for tiling mode please?

**Comment by Unixsys** [comment]
Hello! I've been working on a pseudo-tiling function for a little bit now, and I could start a PR for a patch if interisted. Please note I am a novice when it comes to C programming, so it might not be great, and if so, please point out my errors.

PR is incoming if I can figure out how to do it.

Hope this helps.

**Comment by Unixsys** [comment]
I did a pull request for window splitting: #76 . Hope this helps.

**Comment by Unixsys** [comment]
Please close this issue, has been implimented by #76.
