### ISSUE TITLE
Unexpected behavior of focused window with picom

### ISSUE THREAD

**Issue by Harjuu** [dylanaraps/sowm#79]
I have use picom to blur all currently unfocused windows. In sowm the focused window gets blurred as well, which makes it very difficult to distinguish between focused and unfocused windows, especially when you can't have borders that change colors.

**Comment by dylanaraps** [comment]
Yes. This is likely due to no EWMH/ICCCM support. Borders can also be applied via a patch to sowm. I don't personally use a compositor so this isn't something I've noticed or cared about fixing.
