### ISSUE TITLE
bud not working in arch linux

### ISSUE THREAD

**Issue by ricardoG08** [dylanaraps/sowm#80]
Hello, how do I install the wallpaper cycler "bud" or where can I download and install it ?, apparently in my gnu/linux distribution (arch linux) it doesn't work, regards!

**Comment by dylanaraps** [comment]
https://github.com/dylanaraps/bin/blob/master/bud

**Comment by ghost** [comment]
hi Dylan it may not be important but I have had the need to auto run applications when starting sowm, I leave the code snippet if it works for someone else, or if you can add it to README.md

```bash
#!/bin/sh
# add to ~/.xinitrc
while : ; do
    if ps -A | grep -iq sowm; then
        # add the programs to auto-execute in the script
        sh ~/autostart.sh
        break
    fi
done &
exec sowm
```
