### ISSUE TITLE
Window takes up more space than screen when fullscreened using the border patch

### ISSUE THREAD

**Issue by Unixsys** [dylanaraps/sowm#85]
Hello,

When a window is fullscreened (using my border patch), the window is resized and its size is outside the bounds of the screen. I tried modifying the parameters in ```win_fs``` like so:

```c
void win_fs(const Arg arg) {
    if (!cur) return;

    if ((cur->f = cur->f ? 0 : 1)) {
        win_size(cur->w, &cur->wx, &cur->wy, &cur->ww, &cur->wh);
        XMoveResizeWindow(d, cur->w, 0, 0, sw - BORDER_WIDTH, sh - BORDER_WIDTH);

    } else {
        XMoveResizeWindow(d, cur->w, cur->wx, cur->wy, cur->ww - BORDER_WIDTH, cur->wh - BORDER_WIDTH);
    }
}
```
However, this attempt was futile as the window continued to resize to the wrong position. I realize I should be fixing this problem, as it's my patch, but I don't know how to. One weird thing I noticed is that the window content itself went over the edge of the screen too.

Thanks in advance.

**Comment by viyoriya** [comment]
Update these lines in main method and revert back old code in win_fs

    sw    = XDisplayWidth(d, s) - (2*BORDER_WIDTH);
    sh    = XDisplayHeight(d, s) -(2*BORDER_WIDTH);

if you have panel then
    sh    = XDisplayHeight(d, s) - PANEL_HEIGHT-(2*BORDER_WIDTH);


border width in both sides so (2*)

**Comment by Unixsys** [comment]
Thank you so much for your reply, and your help. I tested this and it works just fine. I'll be adding it in my patch.

Again, thanks so much!

**Comment by Unixsys** [comment]
Thank you so much for your reply, and your help. I tested this and it works just fine. I'll be adding it in my patch.

Again, thanks so much!
