### ISSUE TITLE
Using sxhkd

### ISSUE THREAD

**Issue by LukyIsHere** [dylanaraps/sowm#9]
Is there a way to use sxhkd?

**Comment by dylanaraps** [comment]
There's no IPC type client to interact with `sowm`, however `sxhkd` *can* be used alongside `sowm` solely for keybindings based on spawning external programs. 

Though I don't see the point in using `sxhkd` when shell scripts and other programs can be spawned using `sowm` (*which effectively achieves the same functionality*).
