### ISSUE TITLE
question: when is map_request called?

### ISSUE THREAD

**Issue by Unixsys** [dylanaraps/sowm#92]
Please tell me what ```map_request``` does, and when is it called? I'm want to try to make focused windows a different color than regular windows. Thanks in advance.

**Comment by Unixsys** [comment]
Whoops, md can't be used in title :(

**Comment by dylanaraps** [comment]
`map_request` is called when a window is mapped to the screen, specifically when `sowm` responds to the `MapRequest` event from the Xorg server.

**Comment by Unixsys** [comment]
Thanks.
