### ISSUE TITLE
sowm-almost-tags-1.0.diff crashes sowm on focus

### ISSUE THREAD

**Issue by ahmadsiddeeq0** [dylanaraps/sowm#97]
here is the problem when i apply sowm-almost-tags-1.0.diff patch and press modkey plus 0 to show all the workspaces when i move on one window ( during the modkey plus 0  ) the window manager crashes ?

**Comment by dylanaraps** [comment]
Post this bug in the patch's pull request rather than here. I have nothing to do with the patches.

**Comment by ahmadsiddeeq0** [comment]
the patch's is archived

**Comment by dylanaraps** [comment]
You'll have to contact the author of the patch.
