### ISSUE TITLE
1 && will forever be here. But why?

### ISSUE THREAD

**Issue by astier** [dylanaraps/sowm#98]
Hallo dear @dylanaraps. I was reading your code and was wondering why you have added `1 &&` to the event-loop.
The commit which added it had no explanation. I am just curious. Are there cases when `!XNextEvent(d, &ev)` for some reason quits and terminates sowm although it shouldn't?

https://github.com/dylanaraps/sowm/blob/95596f43aac5f191d96f51290981e860f45eaa55/sowm.c#L275

**Comment by dylanaraps** [comment]
No, it does nothing. Funny mistake I made once, just wanted to remember it.
